repos:
  -  repo: https://github.com/asottile/pyupgrade
     rev: v2.32.1
     hooks:
       -  id: pyupgrade
          args: ["--py39-plus"]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.6.1'
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        files: ^docs/.*\.py$
